# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 05:17
from __future__ import unicode_literals

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observa\xe7\xe3o')),
                ('arquivo', models.FileField(upload_to=dashboard.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descri\xe7\xe3o')),
                ('prioridade', models.PositiveIntegerField(choices=[(1, '1 - M\xednima'), (2, '2 - Baixa'), (3, '3 - Normal'), (4, '4 - Alta'), (5, '5 - Urgente')], default=3)),
                ('status', models.CharField(choices=[('processada', 'processada'), ('done', 'done')], default='Processada', max_length=64)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de cria\xe7\xe3o')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de modifica\xe7\xe3o')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Finalizada por')),
                ('finalizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_finalizada', to=settings.AUTH_USER_MODEL, verbose_name='Finalizada por')),
            ],
        ),
    ]
