# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='observacao',
        ),
        migrations.AddField(
            model_name='anexo',
            name='tarefa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criada por'),
        ),
    ]
